export const constants = {
  SET_OLD_URL: 'PREVIEW_SUMMARY_SET_OLD_URL',
  SET_COMPOUND_IMAGE: 'PREVIEW_SUMMARY_SET_COMPOUND_IMAGE',
  RESET_COMPOUND_IMAGE: 'PREVIEW_SUMMARY_RESET_COMPOUND_IMAGE',
  SET_IS_LOADING_COMPOUND_IMAGE: 'PREVIEW_SUMMARY_SET_IS_LOADING_COMPOUND_IMAGE',

  // summary view
  SET_COUNT_OF_PICKED: 'PREVIEW_SUMMARY_SET_COUNT_OF_PICKED',
  SET_COUNT_OF_EXPLORED_VECTORS: 'PREVIEW_SUMMARY_SET_COUNT_OF_EXPLORED_VECTORS',
  SET_COUNT_OF_EXPLORED_SERIES: 'PREVIEW_SUMMARY_SET_COUNT_OF_EXPLORED_SERIES',
  SET_ESTIMATED_COST: 'PREVIEW_SUMMARY_SET_ESTIMATED_COST',
  SET_SELECTED_INTERACTION: 'PREVIEW_SUMMARY_SET_SELECTED_INTERACTION'
};
