export const constants = {
  SET_OLD_URL: 'PREVIEW_SUMMARY_SET_OLD_URL',
  SET_COMPOUND_IMAGE: 'PREVIEW_SUMMARY_SET_COMPOUND_IMAGE',
  RESET_COMPOUND_IMAGE: 'PREVIEW_SUMMARY_RESET_COMPOUND_IMAGE',
  SET_IS_LOADING_COMPOUND_IMAGE: 'PREVIEW_SUMMARY_SET_IS_LOADING_COMPOUND_IMAGE'
};
