const prefix = 'PREVIEW_SUMMARY_';

export const constants = {
  SET_OLD_URL: prefix + 'SET_OLD_URL',
  SET_COMPOUND_IMAGE: prefix + 'SET_COMPOUND_IMAGE',
  RESET_COMPOUND_IMAGE: prefix + 'RESET_COMPOUND_IMAGE',
  SET_IS_LOADING_COMPOUND_IMAGE: prefix + 'SET_IS_LOADING_COMPOUND_IMAGE',

  // summary view
  SET_COUNT_OF_PICKED: prefix + 'SET_COUNT_OF_PICKED',
  SET_COUNT_OF_EXPLORED_VECTORS: prefix + 'SET_COUNT_OF_EXPLORED_VECTORS',
  SET_COUNT_OF_EXPLORED_SERIES: prefix + 'SET_COUNT_OF_EXPLORED_SERIES',
  SET_ESTIMATED_COST: prefix + 'SET_ESTIMATED_COST',
  SET_SELECTED_INTERACTION: prefix + 'SET_SELECTED_INTERACTION'
};
