const prefix = 'REDUCERS_API_';
export const constants = {
  SET_TARGET_ID_LIST: prefix + 'SET_TARGET_ID_LIST',
  SET_DUCK_YANK_DATA: prefix + 'SET_DUCK_YANK_DATA',
  SET_TARGET_ON: prefix + 'REDUCERS_API_SET_TARGET_ON',

  // Pandda stuff
  SET_PANNDA_SITE_LIST: prefix + 'SET_PANNDA_SITE_LIST',
  SET_PANNDA_EVENT_LIST: prefix + 'SET_PANNDA_EVENT_LIST',
  SET_PANNDA_SITE_ON: prefix + 'SET_PANNDA_SITE_ON',
  SET_PANNDA_EVENT_ON: prefix + 'SET_PANNDA_EVENT_ON',

  SET_MOL_GROUP_ON: prefix + 'SET_MOL_GROUP_ON',
  SET_MOL_GROUP_OFF: prefix + 'SET_MOL_GROUP_OFF',
  SET_MOL_GROUP_LIST: prefix + 'SET_MOL_GROUP_LIST',
  SET_MOLECULE_LIST: prefix + 'SET_MOLECULE_LIST',
  SET_CACHED_MOL_LISTS: prefix + 'SET_CACHED_MOL_LISTS',
  SET_ALL_MOL_LISTS: prefix + 'SET_ALL_MOL_LISTS',
  UPDATE_MOL_IN_ALL_MOL_LISTS: prefix + 'UPDATE_MOL_IN_ALL_MOL_LISTS',
  SET_MOLECULE_TAGS: prefix + 'SET_MOLECULE_TAGS',
  APPEND_MOLECULE_TAG: prefix + 'APPEND_MOLECULE_TAG',
  UPDATE_MOLECULE_TAG: prefix + 'UPDATE_MOLECULE_TAG',

  SET_SAVING_STATE: prefix + 'SET_SAVING_STATE',
  SET_SESH_LIST_SAVING: prefix + 'SET_SESH_LIST_SAVING',
  SET_LATEST_SNAPSHOT: prefix + 'SET_LATEST_SNAPSHOT',
  SET_LATEST_SESSION: prefix + 'SET_LATEST_SESSION',
  SET_SESSION_TITLE: prefix + 'SET_SESSION_TITLE',
  SET_SESSION_ID: prefix + 'SET_SESSION_ID',
  SET_SESSION_ID_LIST: prefix + 'SET_SESSION_ID_LIST',
  UPDATE_SESSION_ID_LIST: prefix + 'UPDATE_SESSION_ID_LIST',
  SET_TARGET_UNRECOGNISED: prefix + 'SET_TARGET_UNRECOGNISED',
  SET_UUID: prefix + 'SET_UUID',
  RELOAD_API_STATE: prefix + 'RELOAD_API_STATE',
  RESET_TARGET_STATE: prefix + 'RESET_TARGET_STATE',
  SET_DIRECT_ACCESS: prefix + 'SET_DIRECT_ACCESS',
  SET_DIRECT_ACCESS_PROCESSED: prefix + 'SET_DIRECT_ACCESS_PROCESSED',
  SET_OPEN_DISCOURSE_ERROR_MODAL: prefix + 'SET_OPEN_DISCOURSE_ERROR_MODAL',
  SET_NO_TAGS_RECEIVED: prefix + 'SET_NO_TAGS_RECEIVED',
  SET_DOWNLOAD_TAGS: prefix + 'SET_DOWNLOAD_TAGS',
  APPEND_TO_DOWNLOAD_TAGS: prefix + 'APPEND_TO_DOWNLOAD_TAGS'
};
