const prefix = 'REDUCERS_SELECTION_';

export const constants = {
  INCREMENT_COUNT_OF_PENDING_VECTOR_LOAD_REQUESTS: prefix + 'INCREMENT_COUNT_OF_PENDING_VECTOR_LOAD_REQUESTS',
  DECREMENT_COUNT_OF_PENDING_VECTOR_LOAD_REQUESTS: prefix + 'DECREMENT_COUNT_OF_PENDING_VECTOR_LOAD_REQUESTS',
  SET_OBJECT_SELECTION: prefix + 'SET_OBJECT_SELECTION',

  SET_TO_BUY_LIST: prefix + 'SET_TO_BUY_LIST',
  APPEND_TO_BUY_LIST: prefix + 'APPEND_TO_BUY_LIST',
  REMOVE_FROM_TO_BUY_LIST: prefix + 'REMOVE_FROM_TO_BUY_LIST',
  SET_INITIAL_FULL_GRAPH: prefix + 'SET_INITIAL_FULL_GRAPH',
  UPDATE_FULL_GRAPH: prefix + 'UPDATE_FULL_GRAPH',
  SET_BOND_COLOR_MAP: prefix + 'SET_BOND_COLOR_MAP',
  SET_TO_QUERY: prefix + 'SET_TO_QUERY',
  SET_VECTOR_LIST: prefix + 'SET_VECTOR_LIST',
  SELECT_VECTOR: prefix + 'SELECT_VECTOR',
  SET_FRAGMENT_DISPLAY_LIST: prefix + 'SET_FRAGMENT_DISPLAY_LIST',
  APPEND_FRAGMENT_DISPLAY_LIST: prefix + 'APPEND_FRAGMENT_DISPLAY_LIST',
  REMOVE_FROM_FRAGMENT_DISPLAY_LIST: prefix + 'REMOVE_FROM_FRAGMENT_DISPLAY_LIST',
  SET_COMPLEX_LIST: prefix + 'SET_COMPLEX_LIST',
  APPEND_COMPLEX_LIST: prefix + 'APPEND_COMPLEX_LIST',
  REMOVE_FROM_COMPLEX_LIST: prefix + 'REMOVE_FROM_COMPLEX_LIST',
  SET_VECTOR_ON_LIST: prefix + 'SET_VECTOR_ON_LIST',
  APPEND_VECTOR_ON_LIST: prefix + 'APPEND_VECTOR_ON_LIST',
  REMOVE_FROM_VECTOR_ON_LIST: prefix + 'REMOVE_FROM_VECTOR_ON_LIST',
  RELOAD_SELECTION_REDUCER: prefix + 'RELOAD_SELECTION_REDUCER',
  RESET_SELECTION_STATE: prefix + 'RESET_SELECTION_STATE',
  SET_MOL_GROUP_SELECTION: prefix + 'SET_MOL_GROUP_SELECTION',
  SET_FILTER_SETTINGS: prefix + 'SET_FILTER_SETTINGS'
};
