export const constants = {
  INCREMENT_COUNT_OF_PENDING_VECTOR_LOAD_REQUESTS: 'INCREMENT_COUNT_OF_PENDING_VECTOR_LOAD_REQUESTS',
  DECREMENT_COUNT_OF_PENDING_VECTOR_LOAD_REQUESTS: 'DECREMENT_COUNT_OF_PENDING_VECTOR_LOAD_REQUESTS',
  SET_OBJECT_SELECTION: 'SET_OBJECT_SELECTION'
};
