const prefix = 'PROJECTS_';

export const constants = {
  SET_CURRENT_PROJECT: prefix + 'SET_CURRENT_PROJECT',
  SET_CURRENT_PROJECT_PROPERTY: prefix + 'SET_CURRENT_PROJECT_PROPERTY',
  RESET_CURRENT_PROJECT_STATE: prefix + 'RESET_CURRENT_PROJECT_STATE',
  SET_PROJECT_MODAL_OPEN: prefix + 'SET_PROJECT_MODAL_OPEN',
  SET_PROJECT_MODAL_IS_LOADING: prefix + 'SET_PROJECT_MODAL_IS_LOADING',
  SET_SNAPSHOT: prefix + 'SET_SNAPSHOT',

  RESET_PROJECTS_REDUCER: prefix + 'RESET_PROJECTS_REDUCER'
};

export const ProjectCreationType = {
  NEW: 'NEW',
  FROM_SNAPSHOT: 'FROM_SNAPSHOT'
};

export const SnapshotType = {
  INIT: 'INIT', // Initial snapshot generated by system
  AUTO: 'AUTO', //Automatic generated by system
  MANUAL: 'MANUAL' //Manual generated by user action
};
