const prefix = 'SESSION_';

export const constants = {
  SET_SAVE_TYPE: prefix + 'SET_SAVE_TYPE',
  SET_NEXT_UUID: prefix + 'SET_NEXT_UUID',
  SET_NEW_SESSION_FLAG: prefix + 'SET_NEW_SESSION_FLAG',
  SET_LOADED_SESSION: prefix + 'SET_LOADED_SESSION',

  SET_OPEN_SAVING_DIALOG: prefix + 'SET_OPEN_SAVING_DIALOG',
  SET_DIALOG_CURRENT_STEP: prefix + 'SET_DIALOG_CURRENT_STEP',
  SET_IS_LOADING_SNAPSHOT_DIALOG: prefix + 'SET_IS_LOADING_SNAPSHOT_DIALOG',

  SET_LIST_OF_SNAPSHOTS: prefix + 'SET_LIST_OF_SNAPSHOTS',
  SET_IS_LOADING_LIST_OF_SNAPSHOTS: prefix + 'SET_IS_LOADING_LIST_OF_SNAPSHOTS',

  SET_SHARED_SNAPSHOT: prefix + 'SET_SHARED_SNAPSHOT',

  SET_IS_OPEN_MODAL_BEFORE_EXIT: prefix + 'SET_IS_OPEN_MODAL_BEFORE_EXIT',
  SET_SELECTED_SNAPSHOT_TO_SWITCH: prefix + 'SET_SELECTED_SNAPSHOT_TO_SWITCH',
  SET_DISABLE_REDIRECT: prefix + 'SET_DISABLE_REDIRECT',

  SET_SNAPSHOT_JUST_SAVED: prefix + 'SET_SNAPSHOT_JUST_SAVED',
  SET_DONT_SHOW_SHARE_SNAPSHOT: prefix + 'SET_DONT_SHOW_SHARE_SNAPSHOT',
  SET_DOWNLOAD_STRUCTURES_DIALOG_OPEN: prefix + 'SET_DOWNLOAD_STRUCTURES_DIALOG_OPEN'
};
