const prefix = 'SESSION_';

export const constants = {
  SET_SAVE_TYPE: prefix + 'SET_SAVE_TYPE',
  SET_NEXT_UUID: prefix + 'SET_NEXT_UUID',
  SET_NEW_SESSION_FLAG: prefix + 'SET_NEW_SESSION_FLAG',
  SET_LOADED_SESSION: prefix + 'SET_LOADED_SESSION',

  SET_OPEN_SAVING_DIALOG: prefix + 'SET_OPEN_SAVING_DIALOG',
  SET_DIALOG_CURRENT_STEP: prefix + 'SET_DIALOG_CURRENT_STEP'
};
