const prefix = 'REDUCERS_NGL_';

export const CONSTANTS = {
  LOAD_OBJECT: prefix + 'LOAD_OBJECT',
  DELETE_OBJECT: prefix + 'DELETE_OBJECT',
  // NGL Component Representation
  UPDATE_COMPONENT_REPRESENTATION: prefix + 'UPDATE_COMPONENT_REPRESENTATION',
  REMOVE_COMPONENT_REPRESENTATION: prefix + 'REMOVE_COMPONENT_REPRESENTATION',
  ADD_COMPONENT_REPRESENTATION: prefix + 'ADD_COMPONENT_REPRESENTATION',

  SET_NGL_VIEW_PARAMS: prefix + 'SET_NGL_VIEW_PARAMS',
  SET_ORIENTATION: prefix + 'SET_ORIENTATION',
  RESET_NGL_VIEW_TO_DEFAULT_SCENE: prefix + 'RESET_NGL_VIEW_TO_DEFAULT_SCENE',
  RESET_NGL_VIEW_TO_SESSION_SCENE: prefix + 'RESET_NGL_VIEW_TO_SESSION_SCENE',
  SAVE_NGL_STATE_AS_DEFAULT_SCENE: prefix + 'SAVE_NGL_STATE_AS_DEFAULT_SCENE',
  SAVE_NGL_STATE_AS_SESSION_SCENE: prefix + 'SAVE_NGL_STATE_AS_SESSION_SCENE',
  REMOVE_ALL_NGL_COMPONENTS: prefix + 'REMOVE_ALL_NGL_COMPONENTS',

  // Helper variables for marking that protein and molecule groups are successful loaded
  SET_PROTEINS_HAS_LOADED: prefix + 'SET_PROTEINS_HAS_LOADED',
  SET_COUNT_OF_REMAINING_MOLECULE_GROUPS: prefix + 'SET_COUNT_OF_REMAINING_MOLECULE_GROUPS',
  DECREMENT_COUNT_OF_REMAINING_MOLECULE_GROUPS: prefix + 'DECREMENT_COUNT_OF_REMAINING_MOLECULE_GROUPS',
  INCREMENT_COUNT_OF_PENDING_NGL_OBJECTS: prefix + 'INCREMENT_COUNT_OF_PENDING_NGL_OBJECTS',
  DECREMENT_COUNT_OF_PENDING_NGL_OBJECTS: prefix + 'DECREMENT_COUNT_OF_PENDING_NGL_OBJECTS',

  SET_MOLECULE_ORIENTATION: prefix + 'SET_MOLECULE_ORIENTATION'
};

export const SCENES = {
  defaultScene: 'defaultScene',
  sessionScene: 'sessionScene'
};
