export const CONSTANTS = {
  LOAD_OBJECT: 'LOAD_OBJECT',
  DELETE_OBJECT: 'DELETE_OBJECT',
  SET_BACKGROUND_COLOR: 'SET_BACKGROUND_COLOR',
  SET_NGL_ORIENTATION: 'SET_NGL_ORIENTATION',
  SET_ORIENTATION: 'SET_ORIENTATION',
  SET_LOADING_STATE: 'SET_LOADING_STATE',
  RESET_NGL_VIEW_TO_DEFAULT_SCENE: 'RESET_NGL_VIEW_TO_DEFAULT_SCENE',
  SAVE_NGL_STATE_AS_DEFAULT_SCENE: 'SAVE_NGL_STATE_AS_DEFAULT_SCENE',
  REMOVE_ALL_NGL_COMPONENTS: 'REMOVE_ALL_NGL_COMPONENTS',

  // Helper variables for marking that protein and molecule groups are successful loaded
  SET_PROTEINS_HAS_LOAD: 'SET_PROTEINS_HAS_LOAD',
  SET_COUNT_OF_REMAINING_MOLECULE_GROUPS: 'SET_COUNT_OF_REMAINING_MOLECULE_GROUPS',
  DECREMENT_COUNT_OF_REMAINING_MOLECULE_GROUPS: 'DECREMENT_COUNT_OF_REMAINING_MOLECULE_GROUPS'
};
