export const CONSTANTS = {
  LOAD_OBJECT: 'LOAD_OBJECT',
  DELETE_OBJECT: 'DELETE_OBJECT',
  // NGL Component Representation
  UPDATE_COMPONENT_REPRESENTATION: 'UPDATE_COMPONENT_REPRESENTATION',
  REMOVE_COMPONENT_REPRESENTATION: 'REMOVE_COMPONENT_REPRESENTATION',
  ADD_COMPONENT_REPRESENTATION: 'ADD_COMPONENT_REPRESENTATION',

  SET_NGL_VIEW_PARAMS: 'SET_NGL_VIEW_PARAMS',
  SET_ORIENTATION: 'SET_ORIENTATION',
  SET_LOADING_STATE: 'SET_LOADING_STATE',
  RESET_NGL_VIEW_TO_DEFAULT_SCENE: 'RESET_NGL_VIEW_TO_DEFAULT_SCENE',
  RESET_NGL_VIEW_TO_SESSION_SCENE: 'RESET_NGL_VIEW_TO_SESSION_SCENE',
  SAVE_NGL_STATE_AS_DEFAULT_SCENE: 'SAVE_NGL_STATE_AS_DEFAULT_SCENE',
  SAVE_NGL_STATE_AS_SESSION_SCENE: 'SAVE_NGL_STATE_AS_SESSION_SCENE',
  REMOVE_ALL_NGL_COMPONENTS: 'REMOVE_ALL_NGL_COMPONENTS',

  // Helper variables for marking that protein and molecule groups are successful loaded
  SET_PROTEINS_HAS_LOADED: 'SET_PROTEINS_HAS_LOADED',
  SET_COUNT_OF_REMAINING_MOLECULE_GROUPS: 'SET_COUNT_OF_REMAINING_MOLECULE_GROUPS',
  DECREMENT_COUNT_OF_REMAINING_MOLECULE_GROUPS: 'DECREMENT_COUNT_OF_REMAINING_MOLECULE_GROUPS',
  INCREMENT_COUNT_OF_PENDING_NGL_OBJECTS: 'INCREMENT_COUNT_OF_PENDING_NGL_OBJECTS',
  DECREMENT_COUNT_OF_PENDING_NGL_OBJECTS: 'DECREMENT_COUNT_OF_PENDING_NGL_OBJECTS'
};

export const SCENES = {
  defaultScene: 'defaultScene',
  sessionScene: 'sessionScene'
};
