---
name: build dev

# Actions that take place after every commit that's not on either the
# staging ore production branches.

# ---------------
# Control secrets
# ---------------
#
# (none)
#
# -----------
# Environment (GitHub Environments)
# -----------
#
# (none)

on:
  push:
    branches-ignore:
    - 'staging'
    - 'production'
    tags-ignore:
    - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      uses: docker/build-push-action@v4
      with:
        tags: ${{ steps.vars.outputs.FE_NAMESPACE }}/fragalysis-frontend:${{ env.GITHUB_REF_SLUG }}
